title: Blog Isui
iconURL: assets/hacker.png
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: #
  github: IsuiLugo
  linkedin: isui-lugo-martinez

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
# hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N